<isomsg direction="incoming">
	<field id="0" value="ISO0260000500200"/>
	<field id="3" value="001000"/>
	<field id="4" value="000000001000"/>
	<field id="7" value="0806204052"/>
	<field id="11" value="020739"/>
	<field id="12" value="151845"/>
	<field id="13" value="0601"/>
	<field id="18" value="5411"/>
	<field id="22" value="010"/>
	<field id="27" value="6"/>
	<field id="32" value="21"/>
	<field id="35" value="4116730010497100=2503"/>
	<field id="37" value="000200922065"/>
	<field id="41" value="P0001001        "/>
	<field id="42" value="7259207        "/>
	<field id="43" value="RESTAURANTE FOUR SEASOCITY         000MX"/>
	<field id="48" value="7450555            00012501"/>
	<field id="49" value="484"/>
	<field id="60" value="B021PRO1*0000000"/>
	<field id="61" value="B317PRO100000000000"/>
	<field id="63" value="@ 0000400082! C000026      00100080     1  000  ! C400012 200210003064! Q200002 02"/>
	<field id="100" value="317"/>
	<field id="120" value="FIRST AVENUE   2             "/>
	<field id="121" value="                    "/>
	<field id="123" value="                    "/>
	<field id="125" value="C5HOSTB24 10"/>
	<field id="126" value="000            00000000000000000000   "/>
</isomsg>