<isomsg direction="incoming">
   	<field id="0" value="ISO0250000550420"/>
   	<field id="3" value="001000"/>
   	<field id="4" value="000000001000"/>
   	<field id="7" value="0601201845"/>
   	<field id="11" value="020739"/>
   	<field id="12" value="151845"/>
   	<field id="13" value="0601"/>
   	<field id="17" value="0601"/>
   	<field id="22" value="012"/>
   	<field id="32" value="90         "/>
   	<field id="35" value="4896350000000040=2403                "/>
   	<field id="37" value="000200922065"/>
   	<field id="38" value="422647"/>
   	<field id="39" value="R9"/>
   	<field id="41" value="00029877        "/>
   	<field id="43" value="SIM_AUTOMATICO        11001BOGOTA  CORCO"/>
   	<field id="48" value="012798831          00000003"/>
   	<field id="49" value="170"/>
   	<field id="60" value="0090TES2*000TES2"/>
   	<field id="61" value="9051000000000000000"/>
   	<field id="90" value="020000000000456405311454229905310000000000"/>
   	<field id="95" value="                                          "/>
   	<field id="100" value="10000009051"/>
   	<field id="121" value="                    "/>
   	<field id="123" value="00000049440000004944"/>
   	<field id="124" value="000000000"/>
   	<field id="125" value="VDB24 B24 1 "/>
   	<field id="126" value="000            2128811                "/>
   	<field id="128" value="6AB46DFE00000000"/>
   </isomsg>