<isomsg direction="incoming">
    <field id="0" value="ISO0050000400800"/>
    <field id="7" value="0129191053"/>
    <field id="11" value="648343"/>
	<field id="53" value="0001000000000000"/>
    <field id="70" value="162"/>
    <field id="120" value="8667  "/>
	<field id="123" value="150CSM(MCL/KSM RCV/9043             ORG/0090             KD/7C4FB37604FA6A608D63E5D365CEF46A CTP/0000000000975B )                                        "/>
	<field id="128" value="0D49C1FB00000000"/>
</isomsg>
